site_name: ORCD Docs
site_url: https://orcd.mit.edu
nav:
  - Home: index.md
  - ORCD Systems: orcd-systems.md
  - Getting Started Tutorial: getting-started.md
  - Accessing ORCD Systems:
    - Logging in with OnDemand: accessing-orcd/ondemand-login.md
    - Logging in with SSH via Terminal: accessing-orcd/ssh-login.md
    - SSH Key Setup: accessing-orcd/ssh-setup.md
    - VSCode Remote SSH: recipes/vscode.md
  - Filesystems and File Transfer:
    - General Use Filesystems:  filesystems-file-transfer/filesystems.md
    - Project Specific Filesystems: filesystems-file-transfer/project-filesystems.md
    - Transferring Files:  filesystems-file-transfer/transferring-files.md
#    - Best Practices:  filesystems-file-transfer/filesystem-best-practices.md
  - Software:
    - Overview: software/overview.md
    - Compiling Codes: software/compile.md
    - Containers: software/apptainer.md
    - Julia: software/julia.md
    - Modules: software/modules.md
    - Python: software/python.md
    - R: software/R.md
    - Other Software: software/building-software.md
#    - Installing Software: 
#    - Singularity/Apptainer: 
#    - Licensed Software: 
  - Running Jobs:
    - Scheduler Overview: running-jobs/overview.md
    - Requesting Resources: running-jobs/requesting-resources.md
    - Job Arrays: running-jobs/job-arrays.md
    - Available Resources: running-jobs/available-resources.md
    - Application Analysis: running-jobs/application-analysis.md
#    - Slurm Partitions: running-jobs/
#    - How To Run Different Workloads: running/page3.md
  - ORCD Recipes:
    - AlphaFold 3: recipes/af3.md
    - GROMACS: recipes/gromacs.md
    - Intel compiler: recipes/intel.md
    - Jupyter: recipes/jupyter.md
    - MPI for Python: recipes/mpi4py.md
    - MPI Jobs: recipes/mpi.md
    - NVHPC with CUDA aware MPI: recipes/nvhpc-a100-with-cuda-and-mpi-example.md
    - ORCA: recipes/orca.md
    - PyCharm: recipes/pycharm.md
    - PyTorch on GPUs - I: recipes/torch-gpu.md
    - PyTorch on GPUs - II: recipes/torch-gpu-intermediate.md
    - RAG: recipes/rag.md
    - RELION: recipes/relion.md
    - VASP: recipes/build-vasp-gcc-cpu.md
    - VSCode: recipes/vscode.md
    - X11: recipes/X11.md
  - Acknowledging Us: acknowledgements.md
  - Data Security and Privacy: data-security.md
  - Acceptable Use and Code of Conduct: code-of-conduct.md
  - Getting Help: getting-help.md
  - FAQs: faqs.md
  - Index: tags.md

theme: 
  name: material
  logo: images/ORCD_logo_icononly.png
  features:
    - content.code.copy
    - content.tabs.link
  palette:
    primary: blue grey
plugins:
  - search
  - tags:
      tags_file: tags.md
  - git-revision-date-localized
  - open-in-new-tab
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - pymdownx.details
  - toc:
      permalink: True
  - attr_list
  - admonition
copyright: <a href="https://accessibility.mit.edu/">Accessibility</a>
