site_name: ORCD Docs
site_url: https://orcd.mit.edu
nav:
  - Home: index.md
  - ORCD Systems: orcd-systems.md
  - Getting Started Tutorial: getting-started.md
  - Filesystems and File Transfer:
    - General Use Filesystems:  filesystems-file-transfer/filesystems.md
    - Project Specific Filesystems: filesystems-file-transfer/project-filesystems.md
    - Transferring Files:  filesystems-file-transfer/transferring-files.md
#    - Best Practices:  filesystems-file-transfer/filesystem-best-practices.md
  - ORCD Recipes:
#    - recipes/gurobi.md
    - MuJoCo: recipes/mujoco.md
    - 'NVHPC with CUDA aware MPI': recipes/nvhpc-a100-with-cuda-and-mpi-example.md
    - GROMACS: recipes/gromacs.md
    - MPI for Python: recipes/mpi4py.md
    - MPI jobs: recipes/mpi.md
    - RELION: recipes/relion.md
    - VSCode: recipes/vscode.md
  - Acknowledging Us: acknowledgements.md
  - Data Security and Privacy: data-security.md
  - Acceptable Use and Code of Conduct: code-of-conduct.md
#  - Basic software and package installation:
#    - Environment Modules: software/page1.md
#    - Installing packages/libraries in Julia, Python, R: software/page2.md
#    - Other software installs/requests: software/page3.md
#  - Running Jobs:
#    - Scheduler Overview: running/page1.md
#    - Slurm Partitions: running/page2.md
#    - How To Run Different Workloads: running/page3.md
#  - How Tos:
#    - howto/page1.md
#    - howto/page2.md
  - Getting Help: getting-help.md
  - Index: tags.md

theme: 
  name: material
  logo: images/ORCD_logo_icononly.png
  features:
    - content.code.copy
    - content.tabs.link
  palette:
    primary: blue grey
markdown_extensions:
    - toc:
        permalink: True
    - attr_list
    - admonition
plugins:
  - search
  - tags:
      tags_file: tags.md
  - git-revision-date-localized
  - open-in-new-tab
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - pymdownx.details
copyright: <a href="https://accessibility.mit.edu/">Accessibility</a>
